name: Build and Release

on:
  release:
    branches
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Test
      run: cd ./internal/teams && go test -v ./...
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build for Linux
      run: go build -o msgteams_linux
      if: success()
    - name: Create release for Linux
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ github.ref }}
        overwrite: true
        release_name:  ${{ github.ref }}
        body: "qualquer coisa"
        prerelease: false
        file: msgteams_linux
      if: success()
    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o msgteams_windows.exe
      if: success()
    - name: Create release for Windows
      uses:  svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ github.ref }}
        overwrite: true
        release_name: ${{ github.ref }}
        body: "qualquer coisa"
        prerelease: false
        file: msgteams_windows.exe
      if: success()
