name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Test
      run: cd ./internal/teams && go test -v ./...
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract version and changes from CHANGELOG.md
      run: |
        version=$(grep '^## \[' CHANGELOG.md | head -n 1 | awk -F '[][]' '{print $2}')
        changes=$(sed -n '/^## \['"$version"'/,/^##/p' CHANGELOG.md | tail -n +2 | head -n -1)
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "changes=$changes" >> $GITHUB_OUTPUT
    - name: Build for Linux
      run: go build -o msgteams_linux
      if: success()
    - name: Create release for Linux
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.version }}
        overwrite: true
        release_name: ${{ env.version }}
        body: ${{ env.changes }}
        prerelease: false
        file: msgteams_linux
      if: success()
    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o msgteams_windows.exe
      if: success()
    - name: Create release for Windows
      uses:  svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.version }}
        overwrite: true
        release_name: ${{ env.version }}
        body: ${{ env.changes }}
        prerelease: false
        file: msgteams_windows.exe
      if: success()
